---
- set_fact:
    services_to_restart: []

- name: Create MinIO Pod
  containers.podman.podman_pod:
    name: minio-pod
    state: started
    network: '{{ minio_podman_network }}'
    hostname: '{{ minio_hostname }}.{{ minio_domain }}'

- debug:
    msg: '{{ minio_mode }}'

- include_tasks: standard.yml
  when: minio_mode == 'standard'

- include_tasks: erasure-code.yml
  when: minio_mode == 'erasure-code'

- include_tasks: nginx.yml

- debug:
    msg: '{{ services_to_restart }}'

- name: daemon-reload
  systemd:
    daemon-reload: yes
  when: services_to_restart | length > 0

- name: Restart Service(s)
  systemd:
    name: '{{ item }}'
    state: restarted
  loop: '{{ services_to_restart }}'
