---
- set_fact:
    services_to_restart: []

- name: Create MinIO Pod
  containers.podman.podman_pod:
    name: minio-pod
    state: started
    network: '{{ minio_podman_network }}'
    hostname: '{{ minio_hostname }}.{{ minio_domain }}'

- debug:
    msg: '{{ minio_mode }}'

- include_tasks: standard.yml
  when: minio_mode == 'standard'

- include_tasks: erasure-code.yml
  when: minio_mode == 'erasure-code'

- include_tasks: nginx.yml

- debug:
    msg: '{{ services_to_restart }}'

- name: daemon-reload
  systemd:
    daemon-reload: yes
  when: services_to_restart | length > 0

- name: Restart Service(s)
  systemd:
    name: '{{ item }}'
    state: restarted
  loop: '{{ services_to_restart }}'

- name: Get Infra Container
  containers.podman.podman_pod_info:
    name: minio-pod
  register: pod_info

- set_fact:
    minio_infra_id: '{{ pod_info.pods[0].InfraContainerID  }}'

- name: Get Infra Container info
  containers.podman.podman_container_info:
    name: '{{ minio_infra_id }}'
  register: container_info

- set_fact:
    minio_pod_ip: '{{ container_info | json_query(query) }}'
  vars:
    query: 'containers[0].NetworkSettings.Networks.{{ minio_podman_network }}.IPAddress'

- debug:
    msg: 'Minio pod IP: {{ minio_pod_ip }}'
