---
- name: Create MinIO data volume
  containers.podman.podman_volume:
    state: present
    name: minio-data-volume
    label:
      app: minio

- name: Run MinIO Container
  containers.podman.podman_container:
    name: minio
    image: docker.io/minio/minio
    pod: minio-pod
    conmon_pidfile: /var/lib/containers/pids/minio.pid
    env:
      MINIO_ACCESS_KEY: '{{ minio_access_key }}'
      MINIO_SECRET_KEY: '{{ minio_secret_key }}'
      MINIO_PROMETHEUS_AUTH_TYPE: '{{ minio_prometheus_auth_type }}'
    volume:
      - minio-data-volume:/data
    command: "server /data"

- name: Generate systemd file for MinIO
  include_tasks: systemd.yml
  loop:
    - minio
